[[education]]
institution="Universidade de Aveiro"
area="New Communication Technologies"
studyType="MSc"
startDate=2003
endDate=2007
gpa="15/20"
subjects=[ "interaction design", "digital video", "creative coding", "web development"]

[[education]]
institution="Universidade de Aveiro"
area="Electronic and Telecommunications Engineering"
studyType="MSc"
startDate=2000
endDate=2003
gpa="Did not graduate"
subjects=[ "math", "physics", "programming", "electronics"]
